import Footer from "@/components/Footer";
import Header from "@/components/Header";
import "@/app/globals.css";

export const metadata = {
  title: "next.js",
  description: "Generated by next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main className="min-h-screen bg-white text-slate-900 dark:bg-slate-900 dark:text-white">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
